### ISSUE TITLE
TLS all the things

### ISSUE THREAD

**Issue by marcoscaceres** [ResponsiveImagesCG/responsiveimages.org#72]
We should encrypt the site

**Comment by marcoscaceres** [comment]
Started setting this up with cloudflare.

**Comment by marcoscaceres** [comment]
Done. Please let me know if there are any issues.

**Comment by nwtn** [comment]
I still can't connect with HTTPS.
![screen shot 2015-05-02 at 9 07 01 am](https://cloud.githubusercontent.com/assets/786799/7441185/aabee6ba-f0aa-11e4-8f1f-05aadf90e303.png)

**Comment by marcoscaceres** [comment]
Talked to dreamhost. For some reason, the registration didn't stick. They are forcing it.

**Comment by marcoscaceres** [comment]
should be fixed in a few hours.

**Comment by marcoscaceres** [comment]
Closing for now... if let's reopen if it happens again tomorrow.

**Comment by marcoscaceres** [comment]
seems to be fine again...
